In [1]:
! pip install ollama sentence-transformers

In [2]:
BOOK_NAMES = [
    "THE SONNETS",
    "ALL’S WELL THAT ENDS WELL",
    "THE TRAGEDY OF ANTONY AND CLEOPATRA",
    "AS YOU LIKE IT",
    "THE COMEDY OF ERRORS",
    "THE TRAGEDY OF CORIOLANUS",
    "CYMBELINE",
    "THE TRAGEDY OF HAMLET, PRINCE OF DENMARK",
    "THE FIRST PART OF KING HENRY THE FOURTH",
    "THE SECOND PART OF KING HENRY THE FOURTH",
    "THE LIFE OF KING HENRY THE FIFTH",
    "THE FIRST PART OF HENRY THE SIXTH",
    "THE SECOND PART OF KING HENRY THE SIXTH",
    "THE THIRD PART OF KING HENRY THE SIXTH",
    "KING HENRY THE EIGHTH",
    "THE LIFE AND DEATH OF KING JOHN",
    "THE TRAGEDY OF JULIUS CAESAR",
    "THE TRAGEDY OF KING LEAR",
    "LOVE’S LABOUR’S LOST",
    "THE TRAGEDY OF MACBETH",
    "MEASURE FOR MEASURE",
    "THE MERCHANT OF VENICE",
    "THE MERRY WIVES OF WINDSOR",
    "A MIDSUMMER NIGHT’S DREAM",
    "MUCH ADO ABOUT NOTHING",
    "THE TRAGEDY OF OTHELLO, THE MOOR OF VENICE",
    "PERICLES, PRINCE OF TYRE",
    "KING RICHARD THE SECOND",
    "KING RICHARD THE THIRD",
    "THE TRAGEDY OF ROMEO AND JULIET",
    "THE TAMING OF THE SHREW",
    "THE TEMPEST",
    "THE LIFE OF TIMON OF ATHENS",
    "THE TRAGEDY OF TITUS ANDRONICUS",
    "TROILUS AND CRESSIDA",
    "TWELFTH NIGHT; OR, WHAT YOU WILL",
    "THE TWO GENTLEMEN OF VERONA",
    "THE TWO NOBLE KINSMEN",
    "THE WINTER’S TALE",
    "A LOVER’S COMPLAINT",
    "THE PASSIONATE PILGRIM",
    "THE PHOENIX AND THE TURTLE",
]

In [3]:
txt = open("shakespeare.txt", "r").read()

books = {}
for book_name, next_book_name in zip(BOOK_NAMES, BOOK_NAMES[1::]):
    book_start = txt.index(book_name)
    book_end = txt.index(next_book_name)
    # print(book_name, book_start, book_end)
    txt = txt[book_end:]
    if "ACT" not in txt[book_start:book_end]:
        pass
    else:
        books[book_name] = txt[book_start:book_end]


In [4]:
scenes = []
for book_name, book in books.items():
    for scene in book.split("\n\n\n"):
        if scene in BOOK_NAMES:
            pass
        elif len(scene) < 30:
            pass
        elif "Contents" in scene:
            pass
        else:
            scenes.append(scene.strip("\n"))


In [5]:
scenes[0]

'ACT II\nScene I. Paris. A room in the King’s palace.\nScene II. Rossillon. A room in the Countess’s palace.\nScene III. Paris. The King’s palace.\nScene IV. Paris. The King’s palace.\nScene V. Another room in the same.'

In [6]:
[len(scene) for scene in scenes]

[213,
 332,
 227,
 153,
 714,
 25588,
 33581,
 22588,
 14722,
 1090,
 25031,
 36115,
 37164,
 29437,
 3868,
 933,
 46,
 27112,
 36,
 23208,
 1267,
 38,
 33582,
 36,
 5465,
 13067,
 35,
 21278,
 610,
 11854,
 12574,
 610,
 11854,
 16101,
 16569,
 22564,
 20298,
 770,
 30,
 36719,
 770,
 30,
 38246,
 37,
 7178,
 19617,
 6672,
 32,
 14539,
 946,
 58,
 34497,
 52,
 6447,
 12783,
 2762,
 56,
 35521,
 50,
 26167,
 40,
 5780,
 34699,
 40,
 699,
 55,
 3132,
 699,
 55,
 38877,
 44,
 33064,
 39,
 41683,
 38,
 30022,
 29,
 15826,
 752,
 27921,
 41116,
 26307,
 3219,
 17132,
 24292,
 40,
 984,
 1778,
 27128,
 5450,
 984,
 1778,
 27128,
 37558,
 19825,
 40169,
 13363,
 1317,
 1467,
 61,
 18283,
 25723,
 33702,
 46871,
 24782,
 33,
 1424,
 34,
 29560,
 32,
 23102,
 47,
 23344,
 35,
 26310,
 35,
 25924,
 1172,
 34,
 20294,
 1172,
 34,
 31479,
 29,
 24710,
 48,
 38637,
 34,
 33815,
 1088,
 44,
 28747,
 63,
 33369,
 50,
 27589,
 35,
 28508,
 25362,
 1194,
 1380,
 54,
 187,
 951,
 1194,
 1380,
 54,
 187

In [7]:
len(scenes)

549

In [8]:
scene_chunks = []
max_length = 4000
for scene in scenes:
    if len(scene) > max_length:
        for i in range(0, len(scene), max_length):
            scene_chunks.append(scene[i : i + max_length])
    else:
        scene_chunks.append(scene)


In [31]:
QUESTION_GENERATION_PROMPT = """
You are reading a chunk of a scene from a shakespeare play.

Please generate 10 questions, separated by newlines, that would be interesting and relevant to ask about the scene.

{scene}
"""

In [54]:
print(scene_chunks[15])

OWN.
O Lord, sir! Nay, put me to’t, I warrant you.

COUNTESS.
You were lately whipp’d, sir, as I think.

CLOWN.
O Lord, sir! Spare not me.

COUNTESS.
Do you cry ‘O Lord, sir!’ at your whipping, and ‘spare not me’? Indeed
your ‘O Lord, sir!’ is very sequent to your whipping. You would answer
very well to a whipping, if you were but bound to’t.

CLOWN.
I ne’er had worse luck in my life in my ‘O Lord, sir!’ I see things may
serve long, but not serve ever.

COUNTESS.
I play the noble housewife with the time, to entertain it so merrily
with a fool.

CLOWN.
O Lord, sir! Why, there’t serves well again.

COUNTESS.
An end, sir! To your business. Give Helen this,
And urge her to a present answer back.
Commend me to my kinsmen and my son.
This is not much.

CLOWN.
Not much commendation to them?

COUNTESS.
Not much employment for you. You understand me?

CLOWN.
Most fruitfully. I am there before my legs.

COUNTESS.
Haste you again.

 [_Exeunt severally._]

SCENE III. Paris. The King’s palace.

 En

In [32]:
import ollama
resp = ollama.generate(model="deepseek-r1:8b", system="", prompt=QUESTION_GENERATION_PROMPT.format(scene=scene_chunks[15]))
resp


GenerateResponse(model='deepseek-r1:8b', created_at='2025-01-23T10:04:45.602533Z', done=True, done_reason='stop', total_duration=66595321042, load_duration=828689084, prompt_eval_count=1183, prompt_eval_duration=14336000000, eval_count=1033, eval_duration=51427000000, response='<think>\nAlright, so I\'ve been given this chunk from Shakespeare\'s play, probably from "Love\'s Labour\'s Lost." The user is asking me to generate 10 questions that would be interesting and relevant to ask about the scene. They want these questions separated by newlines.\n\nFirst, I need to understand the context of the provided text. It seems like it\'s Act III, Scene I in Paris, the king\'s palace. The main characters involved are Bertram, Lafew, Parolles, King, and Helena. The conversation revolves around medical theories, perhaps referencing Galen and Paracelsus, which indicates a discussion about healing or cure methods. There’s also mention of a "heavenly effect in an earthly actor," suggesting some supe

In [34]:
questions = [r.strip() for r in resp.response.split("</think>")[-1].split("\n") if r.strip()]
questions

['1. What is Lafew’s perspective on medical theories like those of Galen and Paracelsus, and how does this reflect his understanding of healing?',
 '2. How does Parolles’ description of a “heavenly effect in an earthly actor” relate to the king’s recovery, and what does this suggest about the healers’ role in the play?',
 '3. What is Helena’s significance in the scene, and how does her claim of being “a simple maid” affect her credibility as a healer?',
 '4. Why does Lafew bring up the idea of dancing a coranto, and how does this physical activity tie into his medical perspective on healing?',
 '5. How does the abrupt transition from medical discussion to dance suggest something about the characters or the setting in this scene?',
 '6. What might Helena’s protestation of being “a simple maid” imply about her character or her role in restoring the king’s health?',
 '7. How does Bertram’s silence and participation in the discussion contribute to our understanding of his character?',
 '8.

In [12]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("joe32140/ModernBERT-base-msmarco", truncate_dim=512)
content_embeddings = model.encode(scene_chunks, batch_size=1, show_progress_bar=True)


/Users/henrymaguire/Work/embeddings/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Batches: 100%|██████████| 10/10 [00:14<00:00,  1.46s/it]


In [13]:
content_embeddings

array([[ 0.55771726,  0.87230176, -0.29413342, ...,  0.12975264,
        -0.11389194, -0.599969  ],
       [ 0.9113775 ,  0.03098609,  0.28880158, ...,  0.8421154 ,
        -0.18530545, -0.51203054],
       [ 0.13367262, -0.6256152 ,  0.68508625, ...,  1.225927  ,
         0.17439255, -0.62599266],
       ...,
       [ 1.7677096 , -1.2551844 , -0.7585908 , ...,  0.09190302,
         0.82426834, -0.8556015 ],
       [ 2.3183877 , -1.8788943 , -0.20429945, ..., -0.48374525,
         0.18929082, -0.580908  ],
       [ 1.9350463 , -2.1134565 , -0.17394446, ..., -1.8323146 ,
        -0.23962176, -0.64766455]], dtype=float32)

In [14]:
scenes[0]

'ACT II\nScene I. Paris. A room in the King’s palace.\nScene II. Rossillon. A room in the Countess’s palace.\nScene III. Paris. The King’s palace.\nScene IV. Paris. The King’s palace.\nScene V. Another room in the same.'

In [35]:
query_embeddings = model.encode(questions, batch_size=1, show_progress_bar=True)

Batches: 100%|██████████| 10/10 [00:11<00:00,  1.17s/it]


In [56]:
sim_to_query = model.similarity(content_embeddings, query_embeddings)
import numpy as np

np.argsort(sim_to_query.mean(-1).reshape(-1))[-5::]

tensor([1621,    5,    7,   11,   15])

In [55]:
sim_to_query.shape

torch.Size([1626, 10])

In [52]:
for i in range(sim_to_query.shape[1]):
    print(questions[i])
    print(np.argsort(sim_to_query[:, i].reshape(-1))[-5::])
    print("\n\n")


1. What is Lafew’s perspective on medical theories like those of Galen and Paracelsus, and how does this reflect his understanding of healing?
tensor([1077,  813,  804,    7,   11])



2. How does Parolles’ description of a “heavenly effect in an earthly actor” relate to the king’s recovery, and what does this suggest about the healers’ role in the play?
tensor([ 365,   15, 1047,  310,    7])



3. What is Helena’s significance in the scene, and how does her claim of being “a simple maid” affect her credibility as a healer?
tensor([ 20, 935, 942, 943,  26])



4. Why does Lafew bring up the idea of dancing a coranto, and how does this physical activity tie into his medical perspective on healing?
tensor([1625,  976,  964,  977,  965])



5. How does the abrupt transition from medical discussion to dance suggest something about the characters or the setting in this scene?
tensor([1072, 1625,  950, 1175, 1578])



6. What might Helena’s protestation of being “a simple maid” imply about h

In [50]:
len(sim_to_query)

1626